Лабораторная работа
Mojiklo/Python_Politech pull request #2
Opened 2024-10-21 18:26 UTC by Mojiklo

2024-10-22 21:04 UTC, rmushkin requested changes
Пожалуйста, исправьте пару мелочей, и дайте мне доступ на запись в репозиторий, чтобы я мог принять и закрыть.

2024-10-22 21:04 UTC, rmushkin commented on task_1.py
> +numbers[4] = ar
[PEP8](https://peps.python.org/pep-0008/) (указания по стилю написания кода): переменные должны называться понятными, осмысленными именами :)
Сокращения можно использовать, только если они общеприняты или есои без них очень плохо.

2024-10-22 21:04 UTC, rmushkin commented on task_3.py
> +col = round((obem / kniga_mb))
[PEP8](https://peps.python.org/pep-0008/): переменные должны называться понятными, осмысленными именами... И пусть они будут на английском.

2024-10-22 21:04 UTC, rmushkin commented on task_3.py
> +col = round((obem / kniga_mb))
В таком виде этот код может привести к ошибке, ведь (например) 99,9 округлится до 100, но если на дискету влезает 99,5 - то сотая книга таки не влезет.

2024-10-22 21:04 UTC, rmushkin commented on task_3.py
> +col = round((obem / kniga_mb))
[PEP8](https://peps.python.org/pep-0008/): избыточные скобки

2024-10-23 19:11 UTC, Mojiklo commented
Здравствуйте! Всё исправила и кинула инвайт на доступ в репозиторий

On Wed, 23 Oct 2024 at 00:05, rmushkin ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Пожалуйста, исправьте пару мелочей, и дайте мне доступ на запись в
> репозиторий, чтобы я мог принять и закрыть.
> ------------------------------
>
> In task_1.py
> <https://github.com/Mojiklo/Python_Politech/pull/2#discussion_r1811399430>
> :
>
> > +su = sum(numbers[:4]) + sum(numbers[5:])
> +co = len(numbers)
> +ar = su / co
> +numbers[4] = ar
>
> PEP8 <https://peps.python.org/pep-0008/> (указания по стилю написания
> кода): переменные должны называться понятными, осмысленными именами :)
> Сокращения можно использовать, только если они общеприняты или есои без
> них очень плохо.
> ------------------------------
>
> In task_3.py
> <https://github.com/Mojiklo/Python_Politech/pull/2#discussion_r1811402460>
> :
>
> > +obem = 1.44
> +co_stronic = 100
> +co_strok = 50
> +co_simv = 25
> +v1simvole = 4
> +
> +kniga_bait = co_stronic * co_strok * co_simv * v1simvole
> +kniga_mb = (kniga_bait) / (1024*1024)
> +
> +col = round((obem / kniga_mb))
>
> PEP8 <https://peps.python.org/pep-0008/>: переменные должны называться
> понятными, осмысленными именами... И пусть они будут на английском.
> ------------------------------
>
> In task_3.py
> <https://github.com/Mojiklo/Python_Politech/pull/2#discussion_r1811409598>
> :
>
> > +kniga_mb = (kniga_bait) / (1024*1024)
> +
> +col = round((obem / kniga_mb))
>
> В таком виде этот код может привести к ошибке, ведь (например) 99,9
> округлится до 100, но если на дискету влезает 99,5 - то сотая книга таки не
> влезет.
> ------------------------------
>
> In task_3.py
> <https://github.com/Mojiklo/Python_Politech/pull/2#discussion_r1811411001>
> :
>
> > +kniga_mb = (kniga_bait) / (1024*1024)
> +
> +col = round((obem / kniga_mb))
>
> PEP8 <https://peps.python.org/pep-0008/>: избыточные скобки
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Mojiklo/Python_Politech/pull/2#pullrequestreview-2386324549>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BL6ZWXYBVNSRF622CQ5UY5LZ424ZBAVCNFSM6AAAAABQKYTTCWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOBWGMZDINJUHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-24 08:38 UTC, rmushkin requested changes
Есть ещё немного микрозамечаний! Пожалуйсте, исправьте.
P. S. Инвайт получил, спасибо!

2024-10-24 08:38 UTC, rmushkin commented on task_3.py
> +book_bait = number_of_pages * number_of_lines * number_of_characters * symbol_weight
Всё-таки он `byte` :)

2024-10-24 08:38 UTC, rmushkin commented on task_3.py
> +book_mb = (book_bait) / (1024*1024)
вокруг первой переменной скобки избыточны

2024-10-24 08:38 UTC, rmushkin commented on task_3.py
> +cound_books = int(volume / book_mb + 0.9999999)
во-первых, coun**t**, а, во-вторых, зачем тут это +0.99999 ???? 😲 Не очень понял, пожалуйста, поясните (или просто исправьте)

2024-10-24 09:19 UTC, Mojiklo commented on task_3.py
> +cound_books = int(volume / book_mb + 0.9999999)
Чтобы избежать округления в меньшую сторону, мы добавили к числу книг единичку и перевели значение в целочисленное с помощью команды int, убирая мантису. int(3.1+1)=4
Но так как может получиться изначально целое значение, то этот метод работать не будет int(3+1) =4
Поэтому мы прибавляем максимально близкое к 1 число - 0.999999: int(3+0.99999) =3 и int(3.9999+0.9999)=int(4.9998)=4

2024-10-25 07:17 UTC, rmushkin commented on task_3.py
> +cound_books = int(volume / book_mb + 0.9999999)
Простите, пожлуйста, я вчера задумался и не ответил...
Смотрите, я, похоже, вас запутал своими комментариями.)

Программирование отличается от вычисления в калькуляторе тем, что мы обычно хотим всё в общем виде, чтобы, подставив в программу любые данные, мы получали правильный (каждый раз разный, но всегда правильный для исходных данных).

Если в вашу исхождную программу подставить другие данные (не 100 страниц, а 76):

```python
# TODO Найдите количество книг, которое можно разместить на дискете

obem = 1.44
co_stronic = 76  # <----- изменено количество страниц
co_strok = 50
co_simv = 25
v1simvole = 4

kniga_bait = co_stronic * co_strok * co_simv * v1simvole
kniga_mb = (kniga_bait) / (1024*1024)

col = round((obem / kniga_mb))

print(col)  # <------ напечатает 4!
```

То получается неправда (в реальности на дискету влезет 3,98 книг, а, значит, целиком - 3). Поэтому проблема как раз с округлением **вверх**, а не вниз. И оно решается просто использованием `int()`, т. к. эта функция как раз и делает простое отбрасывание. Прибавлять 0,99(9) не надо :)

2024-10-25 14:22 UTC, Mojiklo commented on task_3.py
> +cound_books = int(volume / book_mb + 0.9999999)
Поняла. Всё исправила, спасибо!

2024-10-25 14:33 UTC, merged